def set_stylesheet():
	return('#centralWidget {\n'
           'background: #FF8800;\n'
           'border: None;\n'
           '}\n'
           '\n'
           '#top_frame {\n'
           'border: None;\n'
           '}\n'
           '\n'
           '#menu_frame {\n'
           'border: None;\n'
           '}\n'
           '\n'
           '#menu_button {\n'
           'text-align:center;\n'
           'font: 20px;\n'
           'color: #272727;\n'
           'background-color: #FF8800;\n'
           'border-style: solid;\n'
           'border-width: 0px;\n'
           'max-width:40px;\n'
           'max-height:40px;\n'
           'min-width:40px;\n'
           'min-height:40px;\n'
           '}\n'
           '\n'
           '#menu_frame QPushButton:hover {\n'
           'color: #FFFFFF;\n'
           '}\n'
           '\n'
           '#exit_frame {\n'
           'border: None;\n'
           '}\n'
           '\n'
           '#exit_button {\n'
           'text-align:center;\n'
           'font: 18px;\n'
           'color: #272727;\n'
           'border-style: solid;\n'
           'border-width: 0px;\n'
           'border-radius: 25px;\n'
           'max-width:75px;\n'
           'max-height:50px;\n'
           'min-width:75px;\n'
           'min-height:50px;\n'
           '}\n'
           '\n'
           '#exit_button:hover {\n'
           'color: #FFFFFF;\n'
           '}\n'
           '\n'
           '#username_box {\n'
           'text-align:center;\n'
           'background: #272727;\n'
           'font: 12px;\n'
           'color: #FF8800;\n'
           'border-style: solid;\n'
           'border-width: 0px;\n'
           'max-width:175px;\n'
           'max-height:25px;\n'
           'min-width:175px;\n'
           'min-height:25px;\n'
           '}\n'
           '\n'
           '#username_input_frame {\n'
           'border: None;\n'
           '}\n'
           '\n'
           '#scrape_button {\n'
           'text-align:center;\n'
           'font: 18px;\n'
           'color: #FFFFFF;\n'
           'border-style: solid;\n'
           'border-width: 0px;\n'
           'border-radius: 25px;\n'
           'max-width:150px;\n'
           'max-height:50px;\n'
           'min-width:150px;\n'
           'min-height:50px;\n'
           '}\n'
           '\n'
           '#scrape_button:hover {\n'
           'color: #59F3D7;\n'
           '}\n'
           '\n'
           'QLabel {\n'
           'color: #272727;\n'
           'font: 18px;\n'
           'max-height:20px;\n'
           'min-height:20px;\n'
           'max-width:120px;\n'
           'min-width:120px;\n'
           '}\n'
           '\n'
           '\n'
           ''
           '#options_frame {\n'
'background: #232532;\n'
'border: None;\n'
'}\n'
'\n'
'#checks_frame {\n'
'border: None;\n'
'}\n'
'\n'
'#checks_frame QCheckBox {\n'
'color: #FFFFFF;\n'
'font: 10px;\n'
'border: None;\n'
'}\n'
'\n'
'#case_frame {\n'
'border: None;\n'
'}\n'
'\n'
'#characters_frame {\n'
'border: None;\n'
'}\n'
'\n'
'#spins_frame  {\n'
'border: None;\n'
'}\n'
'\n'
'#spins_frame  QLabel {\n'
'font: 10px;\n'
'qproperty-alignment: AlignCenter;\n'
'}\n'
'\n'
'#spins_frame  QSpinBox {\n'
'font: 10px;\n'
'qproperty-alignment: AlignCenter;\n'
'color: #232532;\n'
'}\n'
'\n'
'#spins_frame {\n'
'border: None;\n'
'max-width:250px;\n'
'max-height:50px;\n'
'min-width:225px;\n'
'min-height:50px;\n'
'}\n'
'\n'
'#labels_frame  {\n'
'border: None;\n'
'}\n'
'\n'
'#characters_label_frame  {\n'
'border: None;\n'
'}\n'
'\n'
'#passwords_label_frame  {\n'
'border: None;\n'
'}\n'
'\n'
'#spin_boxes_frame {\n'
'border: None;\n'
'}\n'
'\n'
'\n'
'#close_button_frame {\n'
'border: None;\n'
'}\n'
'\n'
'#close_options_button {\n'
'text-align:center;\n'
'font: 18px;\n'
'color: #FFFFFF;\n'
'border-style: solid;\n'
'border-width: 0px;\n'
'border-radius: 25px;\n'
'max-width:50px;\n'
'max-height:50px;\n'
'min-width:50px;\n'
'min-height:50px;\n'
'}\n'
'\n'
'#close_options_button:hover {\n'
'color: #59F3D7;\n'
'}\n'
'\n'
'QLabel {\n'
'color: #272727;\n'
'font: 18px;\n'
'}\n'
'\n'
'\n'
'')