def set_stylesheet():
	return('#centralWidget {\n'
         'background: #FF8800;\n'
         'border: None;\n'
         '}\n'
         '\n'
         '#top_frame {\n'
         'border: None;\n'
         '}\n'
         '\n'
         '#menu_frame {\n'
         'border: None;\n'
         '}\n'
         '\n'
         '#menu_button {\n'
         'text-align:center;\n'
         'font: 20px;\n'
         'color: #272727;\n'
           'background-color: #FF8800;\n'
           'border-style: solid;\n'
           'border-width: 0px;\n'
           'max-width:40px;\n'
           'max-height:40px;\n'
           'min-width:40px;\n'
           'min-height:40px;\n'
           '}\n'
           '\n'
           '#scrape_frame {\n'
           'border: None;\n'
           '}\n'
           '\n'
           '#scrape_button {\n'
           'text-align:center;\n'
           'font: 18px;\n'
           'color: #272727;\n'
           'border-style: solid;\n'
           'border-width: 0px;\n'
           'border-radius: 25px;\n'
           'max-width:75px;\n'
           'max-height:50px;\n'
           'min-width:75px;\n'
           'min-height:50px;\n'
           '}\n'
           '\n'
           '#scrape_button:hover {\n'
           'color: #FFFFFF;\n'
           '}\n'
           '\n'
           '#menu_frame QPushButton:hover {\n'
           'color: #FFFFFF;\n'
           '}\n'
           '\n'
           '#exit_frame {\n'
           'border: None;\n'
           '}\n'
           '\n'
           '#exit_button {\n'
           'text-align:center;\n'
           'font: 18px;\n'
           'color: #272727;\n'
           'border-style: solid;\n'
           'border-width: 0px;\n'
           'border-radius: 25px;\n'
           'max-width:75px;\n'
           'max-height:50px;\n'
           'min-width:75px;\n'
           'min-height:50px;\n'
           '}\n'
           '\n'
           '#exit_button:hover {\n'
           'color: #FFFFFF;\n'
           '}\n'
           '\n'
           '#username_box {\n'
           'text-align:center;\n'
           'background: #272727;\n'
           'font: 12px;\n'
           'color: #FF8800;\n'
           'border-style: solid;\n'
           'border-width: 0px;\n'
           'max-width:175px;\n'
           'max-height:25px;\n'
           'min-width:175px;\n'
           'min-height:25px;\n'
           '}\n'
           '\n'
           '#number_of_images {\n'
           'text-align:center;\n'
           'background: #272727;\n'
           'font: 12px;\n'
           'color: #FF8800;\n'
           'border-style: solid;\n'
           'border-width: 0px;\n'
           'max-width:175px;\n'
           'max-height:25px;\n'
           'min-width:175px;\n'
           'min-height:25px;\n'
           '}\n'
           '\n'
           '#post_offset {\n'
           'text-align:center;\n'
           'background: #272727;\n'
           'font: 12px;\n'
           'color: #FF8800;\n'
           'border-style: solid;\n'
           'border-width: 0px;\n'
           'max-width:175px;\n'
           'max-height:25px;\n'
           'min-width:175px;\n'
           'min-height:25px;\n'
           '}\n'
           '\n'
           '#set_auth {\n'
           'text-align:center;\n'
           'background: #272727;\n'
           'font: 12px;\n'
           'color: #FF8800;\n'
           'border-style: solid;\n'
           'border-width: 0px;\n'
           'max-width:175px;\n'
           'max-height:25px;\n'
           'min-width:175px;\n'
           'min-height:25px;\n'
           '}\n'
           '\n'
           '#set_auth:hover {\n'
           'color: #FFFFFF;\n'
           'min-height:25px;\n'
           '}\n'
           '\n'
           '#username_input_frame {\n'
           'border: None;\n'
           '}\n'
           '\n'
           'QLabel {\n'
           'color: #272727;\n'
           'font: 10px;\n'
           'max-height:20px;\n'
           'min-height:20px;\n'
           'max-width:75px;\n'
           'min-width:75px;\n'
           '}\n'
           '\n'
           'QLineEdit {\n'
           'text-align:center;\n'
           'background: #272727;\n'
           'font: 12px;\n'
           'color: #FF8800;\n'
           'border-style: solid;\n'
           'border-width: 0px;\n'
           'max-width:350px;\n'
           'max-height:25px;\n'
           'min-width:350px;\n'
           'min-height:25px;\n'
           '}\n'
           '\n'
           '\n'
           ''
           '#options_frame {\n'
          'background: #FF8800;\n'
          'border: None;\n'
          '}\n'
          '\n'
          '#options_frame {\n'
          'border: None;\n'
          '}\n'
          '\n'
          '#options_frame QCheckBox {\n'
          'color: #FFFFFF;\n'
          'font: 10px;\n'
          'border: None;\n'
          '}\n'
          '\n'
          '#case_frame {\n'
          'border: None;\n'
          '}\n'
          '\n'
          '#option_input_frame {\n'
          'border: None;\n'
          '}\n'
          '\n'
          '#labels_frame  {\n'
          'border: None;\n'
          '}\n'
          '\n'
          '#number_label_frame  {\n'
          'border: None;\n'
          '}\n'
          '\n'
          '#offset_label_frame  {\n'
          'border: None;\n'
          '}\n'
          '\n'
          '#offset_label  {\n'
          'border: None;\n'
          'font: 12px;\n'
          '}\n'
          '\n'
          '#number_label  {\n'
          'border: None;\n'
          'font: 12px;\n'
          '}\n'
          '\n'
          '#spin_boxes_frame {\n'
          'border: None;\n'
          '}\n'
          '\n'
          '\n'
          '#close_button_frame {\n'
          'border: None;\n'
          '}\n'
          '\n'
          '#close_options_button {\n'
          'text-align:center;\n'
          'font: 18px;\n'
          'color: #272727;\n'
          'border-style: solid;\n'
          'border-width: 0px;\n'
          'border-radius: 25px;\n'
          'max-width:50px;\n'
          'max-height:50px;\n'
          'min-width:50px;\n'
          'min-height:50px;\n'
          '}\n'
          '\n'
          '#close_options_button:hover {\n'
          'color: #FFFFFF;\n'
          '}\n'
          '\n'
          'QLabel {\n'
          'color: #272727;\n'
          'font: 18px;\n'
          '}\n'
          '\n'
          '\n'
          '')